---
AllCops:
  Exclude:
    - 'vendor/**/*'
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Metrics/ParameterLists:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 12

Style/Documentation:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*'
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/MethodMissing:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false

# bundle exec rubocop -a -D --except Performance/Casecmp
# bundle exec rubocop --auto-gen-config

Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/DuplicatedKey:
  Enabled: false
Lint/IneffectiveAccessModifier:
  Enabled: false
Lint/NonLocalExitFromIterator:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Lint/UnneededDisable:
  Enabled: false
Lint/UselessAccessModifier:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Performance/Casecmp:
  Enabled: false
Performance/DoubleStartEndWith:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/For:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/OptionalArguments:
  Enabled: false
Style/PredicateName:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/VariableName:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
