---
AllCops:
  Excludes:
    - vendor/**
Documentation:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 25
ParameterLists:
  Max: 10
AvoidClassVars:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
