---
sudo: false
language: ruby
matrix:
  include:
    - rvm: "2.2.5"
      env: COMMAND=rake
    - rvm: "2.3.1"
      env: COMMAND=rake
install: bundle install --deployment --without debug
script: bundle exec $COMMAND
