#!/bin/sh
# IBM WebSphere Application Server Liberty Buildpack
# Copyright 2014-2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# this script will write to a file, set-up the filename.
OUTPUT_FILE=$0.txt

# delete file just in case it's already present.
rm -f $OUTPUT_FILE

# write out the command that the buildpack invoked this featureManager script
# with, this will be analysed in the test code to ensure we called this script
# and that it was correctly invoked.
echo 'parameters are ('"$@"')' > $OUTPUT_FILE

# write out the environment variables that should have been set (java home) and
# might have been set, depending on options (jvm args), these will also be
# analysed in test code when necessary.
echo 'java home is ('$JAVA_HOME')' >> $OUTPUT_FILE
echo 'jvm args is ('$JVM_ARGS')' >> $OUTPUT_FILE

# pretend the features requested were already present so we avoid throwing an
# exception from buildpack code (before the test code analyzes the command).
echo "CWWKF1216I"

exit 22
